export { default as Main } from './Main';
export { default as SignIn } from './SignIn';
export { default as SignUp } from './SignUp';
export { default as Password } from './Password';
export { default as BoardAll } from './BoardAll';
export { default as Board } from './Board';
export { default as MakeUp } from './MakeUp';
export { default as Auth } from './Auth';
export { default as QnA } from './QnA';